#!/usr/bin/env ruby

git_bundles = [ 
  "git://github.com/astashov/vim-ruby-debugger.git",
  "git://github.com/ervandew/supertab.git",
  "git://github.com/godlygeek/tabular.git",
  "git://github.com/depuracao/vim-rdoc.git",
  "git://github.com/msanders/snipmate.vim.git",
  "git://github.com/pangloss/vim-javascript.git",
  "git://github.com/scrooloose/nerdtree.git",
  "git://github.com/timcharper/textile.vim.git",
  "git://github.com/tpope/vim-cucumber.git",
  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/tpope/vim-git.git",
  "git://github.com/tpope/vim-haml.git",
  "git://github.com/tpope/vim-markdown.git",
  "git://github.com/tpope/vim-rails.git",
  "git://github.com/tpope/vim-repeat.git",
  "git://github.com/tpope/vim-surround.git",
  "git://github.com/tpope/vim-vividchalk.git",
  "git://github.com/tmhedberg/matchit.git",
  "git://github.com/tsaleh/vim-shoulda.git",
  "git://github.com/tomtom/tcomment_vim.git",
  "git://github.com/tsaleh/vim-tmux.git",
  "git://github.com/vim-ruby/vim-ruby.git",
  "git://github.com/vim-scripts/Gist.vim.git",
  "git://github.com/kchmck/vim-coffee-script.git",
  "git://github.com/elzr/vim-json.git",
  "git://github.com/fatih/vim-go.git",
  "git://github.com/majutsushi/tagbar",
  "git://github.com/vadv/vim-chef",
  "git://github.com/bling/vim-airline",
  "git://github.com/rodjek/vim-puppet",
  "git://github.com/derekwyatt/vim-scala.git",
  "git://github.com/tfnico/vim-gradle.git",
  "git://github.com/ElmCast/elm-vim.git",
  "git://github.com:pearofducks/ansible-vim.git",
  "git://github.com/hashivim/vim-terraform.git",
  "git://github.com/python-mode/python-mode.git",
  "git://github.com:Glench/Vim-Jinja2-Syntax.git"
]

vim_org_scripts = [
  ["IndexedSearch", "plugin"],
  ["jquery", "syntax"],
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end


vim_org_scripts.each do |script_name, script_type|
  puts "downloading #{script_name} at url https://api.github.com/repos/vim-scripts/#{script_name}/#{script_type}/#{script_name}.vim"
  local_file = File.join(script_name, script_type, "#{script_name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("https://raw.githubusercontent.com/vim-scripts/#{script_name}/master/#{script_type}/#{script_name}.vim"
                ).read
  end
end
